{% set major_minor = "2.53" %}
{% set version = major_minor + ".5" %}

package:
  name: glib
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/glib/{{ major_minor }}/glib-{{ version }}.tar.xz
  sha256: 991421f41a4ed4cc1637e5f9db0d03fd236d2cbd19f3c5b097a343bec5126602
  patches:
    # Related to this patch https://bugzilla.gnome.org/show_bug.cgi?id=673135
    # However, it was rejected by upstream. Homebrew decided to keep their own
    # copy ( https://raw.githubusercontent.com/Homebrew/patches/59e4d32/glib/hardcoded-paths.diff ).
    # We are essentially using that copy, but with some tweaks. Info at the link below.
    #
    # https://github.com/Homebrew/legacy-homebrew/blob/21ce7a56cb3fc40fe93d731cc654c69268796772/Library/Formula/glib.rb#L33-L39
    #
    - hardcoded-paths.patch
    # Not sure why test_stdio_wrappers do not pass, skipping it for now.
    - no_fileutils_test.patch

build:
  number: 1
  skip: True  # [not py36]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python 
    - pkg-config      # [unix]
    - libffi >=3.0.0  # [unix]
    - gettext         # [unix]
    - zlib 1.2.11     # [unix]
    - pcre            # [unix]
    - libiconv        # [unix]
    - posix            # [win]
    - m2w64-toolchain  # [win]
    - m2-pkg-config    # [win]
    - m2-libffi >=3.0.0  # [win]
    - m2-gettext-devel         # [win]
    - m2-zlib 1.2.11     # [win]
    - m2-pcre            # [win]
    - m2-libiconv-devel        # [win]
  run:
    - libffi >=3.0.0  # [unix]
    - gettext         # [unix]
    - zlib 1.2.11     # [unix]
    - pcre            # [unix]
    - libiconv        # [unix]
    - posix            # [win]
    - m2w64-gcc-libs   # [win]
    - m2-libffi >=3.0.0  # [win]
    - m2-gettext         # [win]
    - m2-zlib 1.2.11     # [win]
    - m2-pcre            # [win]
    - m2-libiconv        # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libglib-2.0{{ SHLIB_EXT }}  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://developer.gnome.org/glib/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'Provides core application building blocks for libraries and applications written in C.'

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - scopatz
    - ocefpaf
    - pkgw
